### ISSUE TITLE
A Question

### ISSUE THREAD

**Issue by marcussacana** [505e06b2/Chiaki-TV#1]
I have an Mi TV Stick and the Chiaki random freeze the image when I put quality better than 480p, The sound keep playing without problem but the image just freeze, Do you think that is due the Mi TV Stick be too weak to play the stream?

By the way, Will be cool you share the compiled apk as release, it's a pain build from c++, need to download the android sdk and all

**Comment by 505e06b2** [comment]
Just so you know, @thestr4ng3r is the brains behind Chiaki - I really need to get in touch with them to see if I can get my changes merged

That could be the case; you may want to try the most [up-to-date version of Chiaki](https://git.sr.ht/~thestr4ng3r/chiaki/refs) to see if it's been fixed since - if it is, I'll see about merging master in

I did just [publish an APK](https://github.com/505e06b2/Chiaki-TV/releases), though I'm not entirely sure it'll be super useful in the future (still works for me on Quest 2/PS4 though)

**Comment by marcussacana** [comment]
It's fine, thanks, I tried the last version before but no lucky
